// Code generated by qtc from "commitlint.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line commitlint.qtpl:1
package templates

//line commitlint.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line commitlint.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line commitlint.qtpl:1
func StreamCommitlint(qw422016 *qt422016.Writer) {
//line commitlint.qtpl:1
	qw422016.N().S(`
name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

`)
//line commitlint.qtpl:14
}

//line commitlint.qtpl:14
func WriteCommitlint(qq422016 qtio422016.Writer) {
//line commitlint.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line commitlint.qtpl:14
	StreamCommitlint(qw422016)
//line commitlint.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line commitlint.qtpl:14
}

//line commitlint.qtpl:14
func Commitlint() string {
//line commitlint.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line commitlint.qtpl:14
	WriteCommitlint(qb422016)
//line commitlint.qtpl:14
	qs422016 := string(qb422016.B)
//line commitlint.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line commitlint.qtpl:14
	return qs422016
//line commitlint.qtpl:14
}
