// Code generated by qtc from "commitlintconfig.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line commitlintconfig.qtpl:1
package templates

//line commitlintconfig.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line commitlintconfig.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line commitlintconfig.qtpl:1
func StreamCommitlintConfig(qw422016 *qt422016.Writer) {
//line commitlintconfig.qtpl:1
	qw422016.N().S(`
module.exports = {extends: ['@commitlint/config-conventional']}; 

`)
//line commitlintconfig.qtpl:4
}

//line commitlintconfig.qtpl:4
func WriteCommitlintConfig(qq422016 qtio422016.Writer) {
//line commitlintconfig.qtpl:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line commitlintconfig.qtpl:4
	StreamCommitlintConfig(qw422016)
//line commitlintconfig.qtpl:4
	qt422016.ReleaseWriter(qw422016)
//line commitlintconfig.qtpl:4
}

//line commitlintconfig.qtpl:4
func CommitlintConfig() string {
//line commitlintconfig.qtpl:4
	qb422016 := qt422016.AcquireByteBuffer()
//line commitlintconfig.qtpl:4
	WriteCommitlintConfig(qb422016)
//line commitlintconfig.qtpl:4
	qs422016 := string(qb422016.B)
//line commitlintconfig.qtpl:4
	qt422016.ReleaseByteBuffer(qb422016)
//line commitlintconfig.qtpl:4
	return qs422016
//line commitlintconfig.qtpl:4
}
