// Code generated by qtc from "gos2s.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line gos2s.qtpl:1
package templates

//line gos2s.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line gos2s.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line gos2s.qtpl:1
func StreamGoS2S(qw422016 *qt422016.Writer, answer7 string) {
//line gos2s.qtpl:1
	qw422016.N().S(`


import (
        "context"
        "fmt"
        "io"

        "google.golang.org/api/idtoken"
)

// makeGetRequest makes a request to the provided targetURL with an authenticated client.
func makeGetRequest(w io.Writer, targetURL string) error {
        // functionURL := "https://TARGET_URL"
        ctx := context.Background()

        // client is a http.Client that automatically adds an "Authorization" header
        // to any requests made.
        client, err := idtoken.NewClient(ctx, targetURL)
        if err != nil {
                return fmt.Errorf("idtoken.NewClient: %v", err)
        }

        resp, err := client.Get(targetURL)
        if err != nil {
                return fmt.Errorf("client.Get: %v", err)
        }
        defer resp.Body.Close()
        if _, err := io.Copy(w, resp.Body); err != nil {
                return fmt.Errorf("io.Copy: %v", err)
        }

        return nil
}

`)
//line gos2s.qtpl:36
}

//line gos2s.qtpl:36
func WriteGoS2S(qq422016 qtio422016.Writer, answer7 string) {
//line gos2s.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line gos2s.qtpl:36
	StreamGoS2S(qw422016, answer7)
//line gos2s.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line gos2s.qtpl:36
}

//line gos2s.qtpl:36
func GoS2S(answer7 string) string {
//line gos2s.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line gos2s.qtpl:36
	WriteGoS2S(qb422016, answer7)
//line gos2s.qtpl:36
	qs422016 := string(qb422016.B)
//line gos2s.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line gos2s.qtpl:36
	return qs422016
//line gos2s.qtpl:36
}
