// Code generated by qtc from "javascripts2s.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line javascripts2s.qtpl:1
package templates

//line javascripts2s.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line javascripts2s.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line javascripts2s.qtpl:1
func StreamJavascriptS2S(qw422016 *qt422016.Writer, answer7 string) {
//line javascripts2s.qtpl:1
	qw422016.N().S(`

/**
 * TODO(developer): Uncomment these variables before running the sample.
 */
// Example: https://my-cloud-run-service.run.app/books/delete/12345
// const url = 'https://TARGET_HOSTNAME/TARGET_URL';

// Example (Cloud Run): https://my-cloud-run-service.run.app/
// Example (Cloud Functions): https://project-region-projectid.cloudfunctions.net/myFunction
// const targetAudience = 'https://TARGET_HOSTNAME/';
const {GoogleAuth} = require('google-auth-library');
const auth = new GoogleAuth();

async function request() {
  console.info(`)
//line javascripts2s.qtpl:1
	qw422016.N().S("`")
//line javascripts2s.qtpl:1
	qw422016.N().S(`request ${url} with target audience ${targetAudience}`)
//line javascripts2s.qtpl:1
	qw422016.N().S("`")
//line javascripts2s.qtpl:1
	qw422016.N().S(`);
  const client = await auth.getIdTokenClient(targetAudience);
  const res = await client.request({url});
  console.info(res.data);
}

request().catch(err => {
  console.error(err.message);
  process.exitCode = 1;
});

`)
//line javascripts2s.qtpl:27
}

//line javascripts2s.qtpl:27
func WriteJavascriptS2S(qq422016 qtio422016.Writer, answer7 string) {
//line javascripts2s.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line javascripts2s.qtpl:27
	StreamJavascriptS2S(qw422016, answer7)
//line javascripts2s.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line javascripts2s.qtpl:27
}

//line javascripts2s.qtpl:27
func JavascriptS2S(answer7 string) string {
//line javascripts2s.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line javascripts2s.qtpl:27
	WriteJavascriptS2S(qb422016, answer7)
//line javascripts2s.qtpl:27
	qs422016 := string(qb422016.B)
//line javascripts2s.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line javascripts2s.qtpl:27
	return qs422016
//line javascripts2s.qtpl:27
}
