// Code generated by qtc from "nuxtdocker.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line nuxtdocker.qtpl:1
package templates

//line nuxtdocker.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line nuxtdocker.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line nuxtdocker.qtpl:1
func StreamNuxtdocker(qw422016 *qt422016.Writer, portSelected string) {
//line nuxtdocker.qtpl:1
	qw422016.N().S(`
# build stage
FROM node:16-alpine3.14 as build-stage
ENV HOST 0.0.0.0
ENV PORT `)
//line nuxtdocker.qtpl:5
	qw422016.E().S(portSelected)
//line nuxtdocker.qtpl:5
	qw422016.N().S(`
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# production stage
FROM node:16-alpine3.14
WORKDIR /app
EXPOSE `)
//line nuxtdocker.qtpl:15
	qw422016.E().S(portSelected)
//line nuxtdocker.qtpl:15
	qw422016.N().S(`
ENV NODE_ENV=production
ADD package.json ./
ADD nuxt.config.ts ./
COPY --from=build-stage ./app/node_modules ./node_modules/
COPY --from=build-stage ./app/.nuxt ./.nuxt/
COPY --from=build-stage ./app/.output ./.output/
CMD [ "npm", "start" ]
`)
//line nuxtdocker.qtpl:23
}

//line nuxtdocker.qtpl:23
func WriteNuxtdocker(qq422016 qtio422016.Writer, portSelected string) {
//line nuxtdocker.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line nuxtdocker.qtpl:23
	StreamNuxtdocker(qw422016, portSelected)
//line nuxtdocker.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line nuxtdocker.qtpl:23
}

//line nuxtdocker.qtpl:23
func Nuxtdocker(portSelected string) string {
//line nuxtdocker.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line nuxtdocker.qtpl:23
	WriteNuxtdocker(qb422016, portSelected)
//line nuxtdocker.qtpl:23
	qs422016 := string(qb422016.B)
//line nuxtdocker.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line nuxtdocker.qtpl:23
	return qs422016
//line nuxtdocker.qtpl:23
}
