// Code generated by qtc from "redpanda_pub.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line redpanda_pub.qtpl:1
package templates

//line redpanda_pub.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line redpanda_pub.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line redpanda_pub.qtpl:1
func StreamRedpandaPublish(qw422016 *qt422016.Writer, appName string, redpandaTopic string) {
//line redpanda_pub.qtpl:1
	qw422016.N().S(`
const { Kafka } = require('kafkajs')
require("dotenv").config()


const kafka = new Kafka({
  clientId: '`)
//line redpanda_pub.qtpl:7
	qw422016.E().S(appName)
//line redpanda_pub.qtpl:7
	qw422016.N().S(`',
  brokers: [process.env.BROKER_URL1, process.env.BROKER_URL2, process.env.BROKER_URL3],


})


async function pub() {


  const producer = kafka.producer()

  await producer.connect()

  // write data to be publish to broker here
  // can send msg via partition 
  const topicMessages = [
    {
      topic: '`)
//line redpanda_pub.qtpl:25
	qw422016.E().S(redpandaTopic)
//line redpanda_pub.qtpl:25
	qw422016.N().S(`',
      messages: [
        {
          key: 'key1',
          value: 'data1',
          //partition: 0
        },
        {
          key: 'key2',
          value: 'data2',
          //partition: 1
        }
      ],
    }]


  await producer.sendBatch({topicMessages})

  await producer.disconnect()
}

pub()

`)
//line redpanda_pub.qtpl:48
}

//line redpanda_pub.qtpl:48
func WriteRedpandaPublish(qq422016 qtio422016.Writer, appName string, redpandaTopic string) {
//line redpanda_pub.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line redpanda_pub.qtpl:48
	StreamRedpandaPublish(qw422016, appName, redpandaTopic)
//line redpanda_pub.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line redpanda_pub.qtpl:48
}

//line redpanda_pub.qtpl:48
func RedpandaPublish(appName string, redpandaTopic string) string {
//line redpanda_pub.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line redpanda_pub.qtpl:48
	WriteRedpandaPublish(qb422016, appName, redpandaTopic)
//line redpanda_pub.qtpl:48
	qs422016 := string(qb422016.B)
//line redpanda_pub.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line redpanda_pub.qtpl:48
	return qs422016
//line redpanda_pub.qtpl:48
}
