// Code generated by qtc from "redpanda_pub.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line redpanda_pub.qtpl:1
package templates

//line redpanda_pub.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line redpanda_pub.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line redpanda_pub.qtpl:1
func StreamRedpandaPublish(qw422016 *qt422016.Writer, appName string, redpandaTopic string) {
//line redpanda_pub.qtpl:1
	qw422016.N().S(`
const { Kafka } = require('kafkajs')
require("dotenv").config()


const kafka = new Kafka({
  clientId: '`)
//line redpanda_pub.qtpl:7
	qw422016.E().S(appName)
//line redpanda_pub.qtpl:7
	qw422016.N().S(`',
  brokers: [process.env.BROKER_URL1, process.env.BROKER_URL2, process.env.BROKER_URL3],


})


async function pub() {


  const producer = kafka.producer()

  await producer.connect()

  await producer.send({
    topic: '`)
//line redpanda_pub.qtpl:22
	qw422016.E().S(redpandaTopic)
//line redpanda_pub.qtpl:22
	qw422016.N().S(`',
    messages: [
      {
        key: 'my-key',
        value: JSON.stringify({
          some: 'string1',
          some1: 0,
          some2: 'string2,
          some3: 0,
        }),
        partition: 0
      }
    ]
  })

  await producer.disconnect()
  
}

pub()

`)
//line redpanda_pub.qtpl:43
}

//line redpanda_pub.qtpl:43
func WriteRedpandaPublish(qq422016 qtio422016.Writer, appName string, redpandaTopic string) {
//line redpanda_pub.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line redpanda_pub.qtpl:43
	StreamRedpandaPublish(qw422016, appName, redpandaTopic)
//line redpanda_pub.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line redpanda_pub.qtpl:43
}

//line redpanda_pub.qtpl:43
func RedpandaPublish(appName string, redpandaTopic string) string {
//line redpanda_pub.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line redpanda_pub.qtpl:43
	WriteRedpandaPublish(qb422016, appName, redpandaTopic)
//line redpanda_pub.qtpl:43
	qs422016 := string(qb422016.B)
//line redpanda_pub.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line redpanda_pub.qtpl:43
	return qs422016
//line redpanda_pub.qtpl:43
}
