// Code generated by qtc from "sentryaction.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line sentryaction.qtpl:1
package templates

//line sentryaction.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line sentryaction.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line sentryaction.qtpl:1
func StreamSentryaction(qw422016 *qt422016.Writer) {
//line sentryaction.qtpl:1
	qw422016.N().S(`

- uses: actions/checkout@v2
- name: Create Sentry release
  uses: getsentry/action-release@v1
  env:
    SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  with:
    environment: production

`)
//line sentryaction.qtpl:13
}

//line sentryaction.qtpl:13
func WriteSentryaction(qq422016 qtio422016.Writer) {
//line sentryaction.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sentryaction.qtpl:13
	StreamSentryaction(qw422016)
//line sentryaction.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line sentryaction.qtpl:13
}

//line sentryaction.qtpl:13
func Sentryaction() string {
//line sentryaction.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line sentryaction.qtpl:13
	WriteSentryaction(qb422016)
//line sentryaction.qtpl:13
	qs422016 := string(qb422016.B)
//line sentryaction.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line sentryaction.qtpl:13
	return qs422016
//line sentryaction.qtpl:13
}
