// Code generated by qtc from "sonarignore.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line sonarignore.qtpl:1
package templates

//line sonarignore.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line sonarignore.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line sonarignore.qtpl:1
func StreamSonarIgnore(qw422016 *qt422016.Writer, ansSonarIgnore string) {
//line sonarignore.qtpl:1
	qw422016.N().S(`
# sonarcloud will not scan this folder/file
`)
//line sonarignore.qtpl:3
	qw422016.E().S(ansSonarIgnore)
//line sonarignore.qtpl:3
	qw422016.N().S(`

`)
//line sonarignore.qtpl:5
}

//line sonarignore.qtpl:5
func WriteSonarIgnore(qq422016 qtio422016.Writer, ansSonarIgnore string) {
//line sonarignore.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sonarignore.qtpl:5
	StreamSonarIgnore(qw422016, ansSonarIgnore)
//line sonarignore.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line sonarignore.qtpl:5
}

//line sonarignore.qtpl:5
func SonarIgnore(ansSonarIgnore string) string {
//line sonarignore.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
//line sonarignore.qtpl:5
	WriteSonarIgnore(qb422016, ansSonarIgnore)
//line sonarignore.qtpl:5
	qs422016 := string(qb422016.B)
//line sonarignore.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
//line sonarignore.qtpl:5
	return qs422016
//line sonarignore.qtpl:5
}
