// Code generated by qtc from "thctoolkit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line thctoolkit.qtpl:1
package templates

//line thctoolkit.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line thctoolkit.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line thctoolkit.qtpl:1
func StreamThcToolKit(qw422016 *qt422016.Writer, answer1 string, answer2 string, answer3 string, answer4 string, answer5 string, answerTodo string, answerSemantic string, answerTestApi string) {
//line thctoolkit.qtpl:1
	qw422016.N().S(`
# Copyright 2021 The Hacker Collective, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: thcdeployment

on:
  push:
    branches: [ `)
//line thctoolkit.qtpl:20
	qw422016.E().S(answer1)
//line thctoolkit.qtpl:20
	qw422016.N().S(` ]

jobs:
`)
//line thctoolkit.qtpl:23
	qw422016.E().S(answerTodo)
//line thctoolkit.qtpl:23
	qw422016.N().S(`
`)
//line thctoolkit.qtpl:24
	qw422016.E().S(answerSemantic)
//line thctoolkit.qtpl:24
	qw422016.N().S(`
`)
//line thctoolkit.qtpl:25
	qw422016.E().S(answerTestApi)
//line thctoolkit.qtpl:25
	qw422016.N().S(`
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/`)
//line thctoolkit.qtpl:60
	qw422016.E().S(answer2)
//line thctoolkit.qtpl:60
	qw422016.N().S(`:latest .
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/`)
//line thctoolkit.qtpl:63
	qw422016.E().S(answer2)
//line thctoolkit.qtpl:63
	qw422016.N().S(`:latest
      - name: Deploy
        run: |
          gcloud run deploy `)
//line thctoolkit.qtpl:66
	qw422016.E().S(answer2)
//line thctoolkit.qtpl:66
	qw422016.N().S(` \
          --port `)
//line thctoolkit.qtpl:67
	qw422016.E().S(answer3)
//line thctoolkit.qtpl:67
	qw422016.N().S(` \
          --region `)
//line thctoolkit.qtpl:68
	qw422016.E().S(answer4)
//line thctoolkit.qtpl:68
	qw422016.N().S(` \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/`)
//line thctoolkit.qtpl:69
	qw422016.E().S(answer2)
//line thctoolkit.qtpl:69
	qw422016.N().S(` \
          --platform managed \
          --`)
//line thctoolkit.qtpl:71
	qw422016.E().S(answer5)
//line thctoolkit.qtpl:71
	qw422016.N().S(` \
          --quiet \
          --project ${{ secrets.GCP_PROJECT_ID }}
          
`)
//line thctoolkit.qtpl:75
}

//line thctoolkit.qtpl:75
func WriteThcToolKit(qq422016 qtio422016.Writer, answer1 string, answer2 string, answer3 string, answer4 string, answer5 string, answerTodo string, answerSemantic string, answerTestApi string) {
//line thctoolkit.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
//line thctoolkit.qtpl:75
	StreamThcToolKit(qw422016, answer1, answer2, answer3, answer4, answer5, answerTodo, answerSemantic, answerTestApi)
//line thctoolkit.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line thctoolkit.qtpl:75
}

//line thctoolkit.qtpl:75
func ThcToolKit(answer1 string, answer2 string, answer3 string, answer4 string, answer5 string, answerTodo string, answerSemantic string, answerTestApi string) string {
//line thctoolkit.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
//line thctoolkit.qtpl:75
	WriteThcToolKit(qb422016, answer1, answer2, answer3, answer4, answer5, answerTodo, answerSemantic, answerTestApi)
//line thctoolkit.qtpl:75
	qs422016 := string(qb422016.B)
//line thctoolkit.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
//line thctoolkit.qtpl:75
	return qs422016
//line thctoolkit.qtpl:75
}
