// Code generated by qtc from "todoaction.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line todoaction.qtpl:1
package templates

//line todoaction.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line todoaction.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line todoaction.qtpl:1
func StreamTodoaction(qw422016 *qt422016.Writer) {
//line todoaction.qtpl:1
	qw422016.N().S(`
# Copyright 2021 The Hacker Collective, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Todo

on: ["push"]

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.5"
        id: "todo"
`)
//line todoaction.qtpl:28
}

//line todoaction.qtpl:28
func WriteTodoaction(qq422016 qtio422016.Writer) {
//line todoaction.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line todoaction.qtpl:28
	StreamTodoaction(qw422016)
//line todoaction.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line todoaction.qtpl:28
}

//line todoaction.qtpl:28
func Todoaction() string {
//line todoaction.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line todoaction.qtpl:28
	WriteTodoaction(qb422016)
//line todoaction.qtpl:28
	qs422016 := string(qb422016.B)
//line todoaction.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line todoaction.qtpl:28
	return qs422016
//line todoaction.qtpl:28
}
