// Code generated by qtc from "todoaction.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line todoaction.qtpl:1
package templates

//line todoaction.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line todoaction.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line todoaction.qtpl:1
func StreamTodoaction(qw422016 *qt422016.Writer) {
//line todoaction.qtpl:1
	qw422016.N().S(`
 
    name: "Workflow"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "TODO to Issue"
            uses: "alstr/todo-to-issue-action@v4.5"
            id: "todo"

`)
//line todoaction.qtpl:14
}

//line todoaction.qtpl:14
func WriteTodoaction(qq422016 qtio422016.Writer) {
//line todoaction.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line todoaction.qtpl:14
	StreamTodoaction(qw422016)
//line todoaction.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line todoaction.qtpl:14
}

//line todoaction.qtpl:14
func Todoaction() string {
//line todoaction.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line todoaction.qtpl:14
	WriteTodoaction(qb422016)
//line todoaction.qtpl:14
	qs422016 := string(qb422016.B)
//line todoaction.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line todoaction.qtpl:14
	return qs422016
//line todoaction.qtpl:14
}
